
DROP TABLE katstock.stock_item ;
DROP TABLE katstock.place ;
DROP TABLE katstock.place_type ;
DROP TABLE katstock.waybill ;
DROP TABLE katstock.organization ;
DROP TABLE katstock.position ;
DROP TABLE katstock.state ;
DROP TABLE katstock.goods ;
DROP TABLE katstock.measure ;
DROP TABLE katstock.user;
DROP TABLE katstock.stock_organization ;
DROP TABLE katstock.role ;
DROP TABLE katstock.stock ;
DROP TABLE katstock.address ;

DROP SEQUENCE stock_item_seq ;
DROP SEQUENCE waybill_seq ;
DROP SEQUENCE organization_seq ;
DROP SEQUENCE stock_organization_seq ;
DROP SEQUENCE position_seq ;
DROP SEQUENCE state_seq ;
DROP SEQUENCE goods_seq ;
DROP SEQUENCE measure_seq ;
DROP SEQUENCE user_seq ;
DROP SEQUENCE role_seq ;
DROP SEQUENCE stock_seq ;
DROP SEQUENCE address_seq ;
DROP SEQUENCE place_seq ;
DROP SEQUENCE place_type_seq ;
